[project]
name = "metis-post-training-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "httpx",
    "pyarrow",
    "datasets",
    "huggingface_hub",
]
